MasterFox/ExposedAttributes:
  Description: '`exposed_attributes` is our custom JSONAPI extension to make `attributes` public'
  Enabled: true
  VersionAdded: '0.1.0'

MasterFox/ExposedAttribute:
  Description: '`exposed_attribute` is our custom JSONAPI extension to make the `attribute` public'
  Enabled: true
  VersionAdded: '0.1.1'

MasterFox/ExposedHasMany:
  Description: '`exposed_has_many` is our custom JSONAPI extension to make a `has_many` relationship public'
  Enabled: true
  VersionAdded: '0.1.2'

MasterFox/ExposedHasOne:
  Description: '`exposed_has_one` is our custom JSONAPI extension to make a `has_one` relationship public'
  Enabled: true
  VersionAdded: '0.1.3'
